apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
       app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - env:
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: secrets-hawkbit
              key: mysql.user
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secrets-hawkbit
              key: mysql.pwd
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: configmap-hawkbit
              key: DATABASE_NAME
        image: mysql:latest
        name: mysql
        ports:
        - containerPort: 3306
        volumeMounts:
          - name: mysql-data-volume
            mountPath: "/var/lib/mysql"
      restartPolicy: Always
      volumes:
        - name: mysql-data-volume
          persistentVolumeClaim:
            claimName: mysql-pvc

