apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
secretGenerator:
- name: secrets-hawkbit
  literals:
    - mysql.user=root
    - mysql.pwd=secret
    
configMapGenerator:
- name: example-configmap-2
  literals:
  - FOO=Bar
