apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
secretGenerator:
- name: secrets.hawkbit
  literals:
    - mysql.username=root
    - mysql.pwd=secret
    
configMapGenerator:
- name: example-configmap-2
  literals:
  - FOO=Bar

namespace: hawkbit
commonLabels:
  app: hawkbit
resources:
# First create services before we use services
- mysql-service.yaml
- hawkbit-service.yaml
- rabbitmq-service.yaml
# Mysql deployment
- mysql-deployment.yaml


